### ISSUE TITLE
TASK - Split and refactor backend code

### ISSUE THREAD

**Issue by EssKayz** [Ohtu-FaceTed/FaceTed-Search#39]
### Description
Split the python code functionality so that most functions have their own .py file to improve possibilities of simultaneous work without conflicts
Refactor methods to clean the code

### Tasklist
- [x] Split and refactor data loading code into separate file https://github.com/Ohtu-FaceTed/FaceTed-Backend/commit/0e04cd8f0abdb6e6539159f29f15790fd88f7019
- [x] Split and refactor classifier code into separate file https://github.com/Ohtu-FaceTed/FaceTed-Backend/commit/0277272727bcc57aec7bbad09a2e868e7ebccaee
- [x] Refactor tests https://github.com/Ohtu-FaceTed/FaceTed-Backend/commit/0971602d8045f24bd010533505819444f7a45553
- [x] Integrate into app.py https://github.com/Ohtu-FaceTed/FaceTed-Backend/commit/e46939806503f1ff42f343f9232a6ef7db41fff1

**Comment by alafuzof** [comment]
Work in progress on refactor-data branch.
